[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[project]
name = "py_cc_dicts"
version = "1.1.0"
authors = [
  { name="poliwhirl555", email="lesterlinproject@gmail.com" },
]
description = "A library for creating JSONs and accessing the data for the CC-Canto and CC-CEDICT open source Chinese dictionaries."
readme = "pypi_README.md"
requires-python = ">=3.10.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "Topic :: Education",
    "Topic :: File Formats :: JSON"
]
license = "	CC-BY-SA-4.0 AND CC-BY-SA-3.0"
license-files = ["LICEN[CS]E*"]
dependencies = [
  "requests>=2.32.4"
]
keywords = ["JSON", "Cantonese", "Mandarin", "CC-CEDICT", "CC-Canto", "parser", "dictionary", "readings", "CEDICT", "Chinese", "language learning", "education"]
include = [
  "py_cc_dicts/*.py",
  "/tests",
  "*.json",
  "*.zip",
]

[project.urls]
Homepage = "https://github.com/poliwhirl555/cc-canto-edict-jsons"
Issues = "https://github.com/poliwhirl555/cc-canto-edict-jsons/issues"

[tool.hatch.envs.hatch-test]
default-args = ["tests"]
extra-args = ["-vv"]